language: go

go:
  # build version target
  - 1.10.x
  # test against master to see any future breakages
  - master

matrix:
  allow_failures:
    # we build, but we don't particularly care if it fails
    - go: master


# notifications:



before_script:
  - GO_FILES=$(find . -iname '*.go' -type f)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)

after_success:
  - gox -arch="amd64 arm 386" -os="linux" -output="dist/{{.OS}}_{{.Arch}}_{{.Dir}}" ./...
  - ghr --username iggy --replace $(date +%Y%d%m%H%M) dist/
