language: go

go:
  # build version target
  - 1.10.x
  # test against master to see any future breakages
  - master

matrix:
  allow_failures:
    # we build, but we don't particularly care if it fails
    - go: master

# don't build tags ... this stops travis looping when we create a tag to do the release
if: branch = master

notifications:
  slack:
    secure: "HQmH10dvfHzfxWc1XZcia81jP0wCK9aOKLiBMrZA0tiLXxT1Q/3zU00CgO3f4M4wZltbmafOjodO2xMUvZpA8PmoCORR0R0KJaTNJxQRspi0P5IYnbUi875EJQron7SCAWwXR3K4xgozZTfgJGPjS9C6SAa5aRhxkSGRNNw6yHopVuwuAdNtU54SIqfrx9eMBiMd9vb2Y59xiDSnuYiRhC4ZgmxW0tturpWXYZp6LmnID9yGSMi1MXyCMbLMhx067MuPzY3PMwCoHinWedanddMYWxUnzEJLwXlOKoQ9AU8wYth8raryTviWbD/lnA39KoPfcwrZoBKfIWOzm+qUiQ7rglOUpUdtE96Z8VxJkbQMgCW9QqmupxFFiG/3tX5nvqCX7/pmP3m1mTf9AvU23fIuCZPGr/sz2nv8fFYoXLVkDujJG1gcTezhwBpNITDSIEYifSQPr3InUpMCVouQ4QLN+EcDpV3wXcUFxacXoCkZ+tdthMPUllMl2gJpf3NmsWvxK8rtR9RRxwC2/eP/tjnx7fQedWY4eV/Mr8HyxcGzzXv8wsDa14B12uSQ0Gdb6mVqPFgM2mtP/Sc+I7jHuGkwI1jJ9yWFJEDMEL1ESed6wXl7emWo1oMdNNJu+1lR6ca/Y1eZCSwZEpREyioKffsNGZEdPdBFRuC5Q2QWkxw="

services:
  - docker

stages:
  - name: after_success
    if: env(TRAVIS_GO_VERSION) ~= 1.10.*

before_script:
  - export GO_FILES=$(find . -iname '*.go' -type f)
  - export DATETIME=$(date +%Y%d%m%H%M)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  # bunch of tests
  - echo "TRAVIS_GO_VERSION=${TRAVIS_GO_VERSION}"
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)
  # the actual build
  - gox -arch="amd64 arm 386" -os="linux" -output="dist/{{.OS}}_{{.Arch}}_{{.Dir}}" ./...

after_success:
  - ghr --username iggy --replace $DATETIME dist/
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - for dir in input-webhook ; do docker build -t notiggy/scurvy-$dir -f $dir/Dockerfile . ; docker push notiggy/scurvy-$dir ; done

env:
  global:
    - secure: "gr+PcXlQVuvBmBcJLuRlnX1kAKcAirldyVc1PbakHkbQdXnTU9GA/YpNjXzioF2Pj4m1EJ6K5ZenNpDpGg0yi6m9q+TYnCtEvM3tEZoGGgElqPCWXPUhF6ZQLAWOwgGOndsZ/qFkThWDMiARFVyuYpWCtLftzToRef1YW2d6QLN+PWqBFJ3mxL4c8UgIHRfYIGU8aL4Xel11qxzldcYXKYIrSUFmQ7r8sYOwrRXgkVuow7s9daiSCBEmxRIln8Jfm+09nlRwexcqHdgNN37JCzLROGSFFHJW5EVcAncfdE5jFjDfvUU11AGIOw1suM4r2W2Xs0omlUMY7EM4/D0wBgVgWkYoLbRN3rk1YhtWyyj4Va3HN94smolXSD71m5ciWP1E0MhQRSVWRd71yNNmhVOk3QFpc0f4XnOIhRRassnDENhhlR//e0URfkXj58/I53/lelYWNiHzlvRwl2NIYYAuStm5gkqbl3HKCdqIZisGL1gcb6GBiAL2CWfsAquhgNB0orIdagTQQ9QAp4ykmvf5TIZOGgr+zqm2ELSxEX0YjY650lz9KHTSshS5Ih0+eQSj6Q9LVwt1zZhEUFyHwsRBUpG+flSKhjjmhX6ga124BBokLVsO6BBCjzFxBaPPdKQopyjLhkxuRcxYnYU6XQwH6UEyFQxeuoFGLQ7pyUo="
    - secure: "OPU/EU0w1CiqNC1btrOtXMvnT2k89T42gfsV3O1VaRWSnKqMXwc89kskSgl0JlIUte0MyLuqXwfHAQ00NalIY0yq8fCpmfcYGRue5BpYsgp2nN98U9Rg8YrWU/OfXn/NNKhVbrB+iJU7ShRJMTAn3lecc18QQhmI2WwjxfPkkSm4+Xet9GZ1ex+Nipno7EZtRCPl5NTdJhShFCeSgPO1MKZydzpSEdC3YC9qP157gKVsAXi31si4+3Z5/BTGOK32PaQaAwKjqe5rl6KfHuFj4WG7XOCD271tnGpoWIB9+N3BS5XdXwQ+loAN614d0Yr1yxxfTdjyrv72LM/aygqoihRk08LJQVJnVEVyAaMdK7TpX0bUaDkgnZ0Zgyo2PEJonYGKCtgGsVWjM2fxCEuZZGF+NSwL5nkwZLit49WHwFqSAWJTggc1y2FG7EpvP4lBbUB5bsbA9NkP8kzCnwwg8qWpxWx+KGmfrmYdmKtxOcojWpoEBj7ZYmSO3gPN3uKF0yCo3+tVZGiiBEJnPmo8Jgazp3sqZrzFWpTa6UpwCpp4jEk4aeSJPpd9w08trU/YgHohFMaiLtpjbg7sGKMAqZWUihmzWBjNMa+K/B/KnTrjA0uT+Y4QQOUk83TRYY1+xpevTIN9lEEDFg6ruKpupgmlVnZsss+3vlHe5Y65MOQ="
    - secure: "a73EfzOeZExEGs1VNwWsDChDOqL+YybM2KFsd4fxeFxfaol4aNrnjNhYqO/OMcG/qyNA7pEHWWCgLxhhx5Vm6XXzj+/SNRPILZq/i00+J+f0SsnCyR9ydz+Rf8iOhKkYv5ru+ixuoXy+/bgzz3/FOtDPEo/RgmX0wTZi/RoPoQElU9KrVxzTP71q2xfXErzyvONN/Dbq/sWsFVOBvtxb2usMAtXf+0EtGqWJV4J+GugBDpxMlfC6ZBFuepfa5iOxTkf8eQEfKQDZRFoP3r+WahcXwHzIRiLrPAr4lKOXCyj/n91nf75FdH9vdaS36bDBDGfatl5zLyY/G0huBZAy0CJFLpupUqiGe42qVvAigPsAqahM2+V7fD7I24RXn/+Nv+f1PTfLpmZsEmTNJkBDtalaWKH6h1kT/9btfJTuVI3+5whXvkspLv3UlXIeOJz72yFarKl4e3wN9yQjz/FyBCorlrXdQFzFLbWxMw1BphcoqS0wA6bmpiU2RhM2Zx/3XFHWyBoZ4n+U4VV0AuDxVjPejxgxcQHajUJ5DwcPhCzNO2BXo+ixU9kxCMxXY2KtjUvRbMdztBlxfE86W85AXa8HP1P0teDxUoxt6PvTGrlDa5nLZnc9inbocwYMdo/mWIy5d7wvFKM43ES7h4kFF5nRi1A4hCuoDUt+NM4I0aU="
