# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # enable docker in CircleCI
      - setup_remote_docker:
          docker_layer_caching: true

      # specify any bash command here prefixed with `run: `
      - run: make docker

  deploy:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      # enable docker in CircleCI
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


# GITHUB_TOKEN, DOCKER_USER, DOCKER_PASS env variables are set in CircleCI config
