# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#
# Notes:
# * docker_layer_caching is only available to paid accounts
# * GITHUB_TOKEN, DOCKER_USER, DOCKER_PASS env variables are set in CircleCI config
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/iggy/scurvy
    steps:
      - run: env
      - checkout
      # enable docker in CircleCI
      - setup_remote_docker
      - run: make docker
      - run: docker version ; docker images

  deploy:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/iggy/scurvy
    steps:
      - run: env
      # enable docker in CircleCI
      - setup_remote_docker
      - run: docker version ; docker images
      - run: make release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
