---
name: buildx for arm/arm64/amd64

'on':
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build/push image
    env:
      PUBLISH: ${{ github.ref == 'master' }}
    strategy:
      matrix:
        target:
          - irc
          - input-webhook
          - notifyd
          - syncd
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish ${{ matrix.target }} image
        uses: ilteoood/docker_buildx@1.0.4
        with:
          publish: ${{ env.PUBLISH }}
          imageName: notiggy/scurvy-${{ matrix.target }}
          target: ${{ matrix.target }}
          dockerHubUser: ${{ secrets.DH_USER }}
          dockerHubPassword: ${{ secrets.DH_PASS }}
