---
name: buildx for arm/arm64/amd64

'on':
  push:
  pull_request:
    branches:
      - master

jobs:
  super-linter:
    runs-on: ubuntu-latest
    name: Run GitHub's Super Linter
    steps:
      - uses: actions/checkout@v2
      - name: Super Linter
        # This makes it pull from github's docker repo according to a note in the README.md
        uses: docker://github/super-linter:v3
        env:
          # super-linter runs golangci-lint in a stupid way, just disable it
          # and run it separately below
          VALIDATE_GO: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci-lint:
    name: golangci-lint on push
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch
          # version.
          version: v1.33

  build:
    runs-on: ubuntu-latest
    name: Build/push image
    strategy:
      matrix:
        target:
          - irc
          - input-webhook
          - notifyd
          - syncd
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Build and publish ${{ matrix.target }} image
        uses: ilteoood/docker_buildx@1.1.0
        env:
          PUBLISH: ${{ github.ref == 'refs/heads/master' }}
          PUBLISH2: ${{ contains(github.ref, 'master') }}
          REF: ${{ github.ref }}
        with:
          publish: ${{ env.PUBLISH }}
          imageName: notiggy/scurvy-${{ matrix.target }}
          target: ${{ matrix.target }}
          dockerHubUser: ${{ secrets.DH_USER }}
          dockerHubPassword: ${{ secrets.DH_PASS }}
