---
name: buildx for arm/arm64/amd64

'on':
  push:
  pull_request:
    branches:
      - master

jobs:
  super-linter:
    runs-on: ubuntu-latest
    name: Run GitHub's Super Linter
    steps:
      - uses: actions/checkout@v2
      - name: Super Linter
        uses: docker://github/super-linter@v1.0.0

  build:
    runs-on: ubuntu-latest
    name: Build/push image
    strategy:
      matrix:
        target:
          - irc
          - input-webhook
          - notifyd
          - syncd
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish ${{ matrix.target }} image
        uses: ilteoood/docker_buildx@1.0.4
        env:
          PUBLISH: ${{ github.ref == 'refs/heads/master' }}
          PUBLISH2: ${{ contains(github.ref, 'master') }}
          REF: ${{ github.ref }}
        with:
          publish: ${{ env.PUBLISH }}
          imageName: notiggy/scurvy-${{ matrix.target }}
          target: ${{ matrix.target }}
          dockerHubUser: ${{ secrets.DH_USER }}
          dockerHubPassword: ${{ secrets.DH_PASS }}
